name: Building recovery

env:
      FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
      CONFIG: config.sh
      CIRRUS_SHELL: bash
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TG_TOKEN: ${{ secrets.TG_TOKEN }}

on: [push]

jobs:
  recovery-build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/sushrut1101/docker:latest
      
    steps:
       - uses: actions/checkout@v2
       - name: OrangeFox-CI
         run: |
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/checks.sh | bash
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh | bash
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh | bash
            export TIMEOUT=43200 # Link timeout (in minutes)
            curl https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/upload.sh | bash
