name: Building recovery

on:
  push:
    branches: [ main ]

env:
  FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
  CONFIG: config.sh
  CIRRUS_SHELL: bash
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  
jobs:
  Checks:
    runs-on: ubuntu-20.04

    container: 
      image: ghcr.io/sushrut1101/docker:latest
      
    steps:
       - name: Checkout
         uses: actions/checkout@v2
         
       - name: Checks_script
         run: |
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/checks.sh | bash

       - name: Sync_script
         run: |
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/sync.sh | bash

       - name: Build_script
         run: |
            curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/build.sh | bash

       - name: Upload_script
         run: |
            export TIMEOUT=43200 # Link timeout (in minutes)
            curl https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/scripts/upload.sh | bash
